[package]
name = "ternary-kernels"
version = "0.1.0"
edition = "2021"

[dependencies]
ternary-core = { path = "../ternary-core" }
rayon = { workspace = true }
once_cell = "1.20"
log = "0.4"

[features]
cuda = []
autotune = []

[build-dependencies]
cc = "1.0"
